name: CI/CD - Build and Deploy to EC2

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: 소스 코드를 runner에 체크아웃
        uses: actions/checkout@v4

      - name: JDK 21 설치 및 설정 (corretto 배포판 사용)
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Gradle Wrapper 파일에 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 운영 application.yml 추가
        run: |
          echo "${{ secrets.PROD_YML }}" > src/main/resources/application-prod.yml

      - name: secrets 디렉토리 생성 후 secrets.yml 추가
        run: |
          mkdir -p src/main/resources/secrets
          echo "${{ secrets.SECRETS_YML }}" > src/main/resources/secrets/secrets.yml 

      - name: Gradle로 빌드 및 테스트 실행
        run: ./gradlew clean build --no-daemon -x test

      - name: 빌드 결과물 업로드
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: build/libs/*.jar

      - name: EC2 접속을 위한 SSH 키 설정
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/ec2.pem
          chmod 600 ~/.ssh/ec2.pem

      - name: JAR를 EC2로 복사
        run: |
          scp -i ~/.ssh/ec2.pem -o StrictHostKeyChecking=no ./build/libs/*.jar ubuntu@${{ secrets.EC2_HOST }}:/opt/scheduler/

      - name: Restart systemd service on EC2
        run: |
          ssh -i ~/.ssh/ec2.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << EOF
            sudo systemctl restart scheduler.service
          EOF
